### ISSUE TITLE
Contribute to ExtensionIndex ( nightly builds in slicer )

### ISSUE THREAD

**Issue by phcerdan** [KitwareMedical/SlicerSkeletalRepresentation#2]
https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/Contribute_Extension_Description_File

**Comment by phcerdan** [comment]
@ZhiyLiu thanks for the contribution the extension file. I see you have opened a PR in ExtensionIndex already: https://github.com/Slicer/ExtensionsIndex/pull/1578, that's great.

It seems we are missing one or two points that @lassoan mentioned needed for integration. Let us know if you need help. Thanks.

**Comment by ZhiyLiu** [comment]
Here is a checklist, pls add some comments below:

- [Use "SkeletalRepresentation" instead ] Extension has a reasonable name: maybe SkeletalShapeRepresentation would be more descriptive

 

- [ Done] Repository name has to be Slicer (e.g., SlicerSkeletalShapeRepresentation)

- [Done ] s4ext Extension description: make it a bit more informative for people who are not already familiar with the project

- [ Change from my fork branch to KitwareMedical] consider using a branch name instead of a specific git has to avoid re-submitting pull request whenever you make a change in your extension

- [ Keep current URL] s4ext Extension icon URL is correct

- [ Fixed] s4ext Screenshot URLs (screenshoturls) are incorrect

- [Done ] README.md needs improvement:

**Comment by ZhiyLiu** [comment]
I fixed these on the original branch[ Add s rep extension #1578](https://github.com/Slicer/ExtensionsIndex/pull/1578). Should I create one new branch for overall changes?

**Comment by ZhiyLiu** [comment]
Done in Slicer/ExtensionsIndex#1582
